# 项目相关配置
oa:
  profile: E:/oa/uploadPath
  # 获取ip地址开关
  addressEnabled: false
  # 验证码类型 math 数字计算 char 字符验证
  captchaType: math
  bpmnPath: C:\Users\battl\Desktop

# 开发环境配置
server:
  # 服务器的HTTP端口，默认为8080
  port: 8081
  servlet:
    # 应用的访问路径
    context-path: /oa
  tomcat:
    # tomcat的URI编码
    uri-encoding: UTF-8
    # 连接数满后的排队数，默认为100
    accept-count: 1000
    threads:
      # tomcat最大线程数，默认为200
      max: 800
      # Tomcat启动初始化的线程数，默认值10
      min-spare: 100

# 日志配置
logging:
  level:
    root: info
    com.oa: debug
    org.springframework: warn
    org.flowable: info
    com.central: INFO
    org.springframework.web: INFO
    org.hibernate: INFO
    org.hibernate.type.descriptor.sql.BasicBinder: TRACE
    org.hibernate.type.descriptor.sql.BasicExtractor: TRACE

# 用户配置
user:
  password:
    # 密码最大错误次数
    maxRetryCount: 5
    # 密码锁定时间（默认10分钟）
    lockTime: 10

# Spring配置
spring:
  # 资源信息
  messages:
    # 国际化资源文件路径
    basename: i18n/messages
  jackson:
    serialization:
      write-dates-as-timestamps: true
  profiles:
    active: prod
  # 文件上传
  servlet:
    multipart:
      # 单个文件大小
      max-file-size: 10MB
      # 设置总上传的文件大小
      max-request-size: 20MB
  # redis 配置
  redis:
    # 地址
    host: zhaokai.xyz
    # 端口，默认为6379
    port: 6379
    # 数据库索引
    database: 0
    # 密码
    password: qizhi@2307
    # 连接超时时间
    timeout: 10s
    lettuce:
      pool:
        # 连接池中的最小空闲连接
        min-idle: 0
        # 连接池中的最大空闲连接
        max-idle: 8
        # 连接池的最大数据库连接数
        max-active: 8
        # #连接池最大阻塞等待时间（使用负值表示没有限制）
        max-wait: -1ms
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driverClassName: com.mysql.cj.jdbc.Driver
    druid:
      # 主库数据源
      master:
        url: jdbc:mysql://zhaokai.xyz:3306/oa_core?useUnicode=true&characterEncoding=utf8&zeroDateTimeBehavior=convertToNull&useSSL=true&serverTimezone=GMT%2B8
        username: root
        password: 7a14b92569085afd
      # 从库数据源
      flowable:
        # 从数据源开关/默认关闭
        url: jdbc:mysql://zhaokai.xyz:3306/oa_flowable?allowMultiQueries=true&useUnicode=true&characterEncoding=UTF-8&autoReconnect=true&useSSL=false&zeroDateTimeBehavior=convertToNull&serverTimezone=Asia/Shanghai&nullCatalogMeansCurrent=true
        username: root
        password: 7a14b92569085afd
      # 初始连接数
      initialSize: 5
      # 最小连接池数量
      minIdle: 10
      # 最大连接池数量
      maxActive: 20
      # 配置获取连接等待超时的时间
      maxWait: 60000
      # 配置连接超时时间
      connectTimeout: 30000
      # 配置网络超时时间
      socketTimeout: 60000
      # 配置间隔多久才进行一次检测，检测需要关闭的空闲连接，单位是毫秒
      timeBetweenEvictionRunsMillis: 60000
      # 配置一个连接在池中最小生存的时间，单位是毫秒
      minEvictableIdleTimeMillis: 300000
      # 配置一个连接在池中最大生存的时间，单位是毫秒
      maxEvictableIdleTimeMillis: 900000
      # 配置检测连接是否有效
      validationQuery: SELECT 1 FROM DUAL
      testWhileIdle: true
      testOnBorrow: false
      testOnReturn: false
      webStatFilter:
        enabled: true
      statViewServlet:
        enabled: true
        # 设置白名单，不填则允许所有访问
        allow:
        url-pattern: /druid/*
        # 控制台管理用户名和密码
        login-username: oa
        login-password: 123456
      filter:
        stat:
          enabled: true
          # 慢SQL记录
          log-slow-sql: true
          slow-sql-millis: 1000
          merge-sql: true
        wall:
          config:
            multi-statement-allow: true

# token配置
token:
  # 令牌自定义标识
  header: Authorization
  # 令牌密钥
  secret: OA-System:Copyright@2024-2025:zhaokai.xyz:All:Rights:Reserverd:BoEdge:JWT-Signature-Key
  # 令牌有效期（默认30分钟）
  expireTime: 10080

# MyBatis配置
mybatis:
  # 搜索指定包别名
  typeAliasesPackage: com.oa.**.domain
  # 配置mapper的扫描，找到所有的mapper.xml映射文件
  masterMapperLocations: classpath*:mapper/master/**/*Mapper.xml
  flowableMapperLocations: classpath*:mapper/flowable/**/*Mapper.xml
  # 加载全局的配置文件
  configLocation: classpath:mybatis/mybatis-config.xml

# PageHelper分页插件
pagehelper:
  helperDialect: mysql
  supportMethodsArguments: true
  params: count=countSql

# Swagger配置
swagger:
  # 是否开启swagger
  enabled: true
  # 请求前缀
  pathMapping: /dev-api

# 防止XSS攻击
xss:
  # 过滤开关
  enabled: true
  # 排除链接（多个用逗号分隔）
  excludes: /system/notice
  # 匹配链接
  urlPatterns: /system/*,/monitor/*,/tool/*

flowable:
  # 不自动部署
  check-process-definitions: false
  security:
    enable: false

huawei:
  obs:
    accessKeyId: ZH7YEZQZESXDGZA0E8PA
    secretAccessKeyId: SFc7gJfgVpu5PaOgp8QC7rHKiaTCLGKFcGPWRA2L
    endPoint: obs.cn-east-3.myhuaweicloud.com
    bucketName: aka-noodle

recaptcha:
  secret: 6LfqEDoqAAAAADE9wqp0jrqgVOy6EIO1FxA61doh
  url: https://recaptcha.net/recaptcha/api/siteverify

coze:
  clientId: 1128122243349
  publicKey: a2dt0UBzJRdIOw97XlW15yryTSX3AnUmz59JTDKBlQ0